### ISSUE TITLE
Thought Sieve requires the same start position as requested pattern

### ISSUE THREAD

**Issue by Aspurgus** [dashkal16/HexResearch#3]
Its as the title says. If you write to a scroll the great spell shape, but have a different start and endpoint to the generated great spell's pattern, the spell doesn't recognize it as a scroll that contains a great spell. I don't know if this is by design or not

**Comment by dashkal16** [comment]
Not by design, no.  I'll have to get that fixed.  Thanks!

**Comment by dashkal16** [comment]
I am failing to reproduce this locally.  Which spell specifically?
